import type { GabaritoPenseBem } from "./081";

export const GABARITO_PENSE_BEM: GabaritoPenseBem = {
  programa_1: [
    { questao: 1, cor: "Verde", resposta: "alimentos" },
    { questao: 2, cor: "Vermelho", resposta: "fast food" },
    { questao: 3, cor: "Vermelho", resposta: "energia" },
    { questao: 4, cor: "Vermelho", resposta: "refrigerante" },
    { questao: 5, cor: "Azul", resposta: "carro" },
    { questao: 6, cor: "Verde", resposta: "Sonic" },
    { questao: 7, cor: "Azul", resposta: "fugir" },
    { questao: 8, cor: "Vermelho", resposta: "saltar" },
    { questao: 9, cor: "Vermelho", resposta: "amigo" },
    { questao: 10, cor: "Azul", resposta: "respirar" },
    { questao: 11, cor: "Verde", resposta: "mergulhar" },
    { questao: 12, cor: "Amarelo", resposta: "porquinho" },
    { questao: 13, cor: "Azul", resposta: "circular" },
    { questao: 14, cor: "Verde", resposta: "pneu" },
    { questao: 15, cor: "Verde", resposta: "velocidade" },
    { questao: 16, cor: "Amarelo", resposta: "acelerador" },
    { questao: 17, cor: "Verde", resposta: "forma" },
    { questao: 18, cor: "Verde", resposta: "guepardo" },
    { questao: 19, cor: "Amarelo", resposta: "pião" },
    { questao: 20, cor: "Verde", resposta: "luz" },
    { questao: 21, cor: "Vermelho", resposta: "iluminado" },
    { questao: 22, cor: "Azul", resposta: "sombra" },
    { questao: 23, cor: "Vermelho", resposta: "escuro" },
    { questao: 24, cor: "Azul", resposta: "contrário" },
    { questao: 25, cor: "Vermelho", resposta: "sombra do Sonic" },
    { questao: 26, cor: "Vermelho", resposta: "lâmpada" },
    { questao: 27, cor: "Vermelho", resposta: "A" },
    { questao: 28, cor: "Amarelo", resposta: "B" },
    { questao: 29, cor: "Azul", resposta: "C" },
    { questao: 30, cor: "Verde", resposta: "D" },
  ],
  programa_2: [
    { questao: 31, cor: "Azul", resposta: "computador" },
    { questao: 32, cor: "Verde", resposta: "Sonic" },
    { questao: 33, cor: "Vermelho", resposta: "funil" },
    { questao: 34, cor: "Amarelo", resposta: "ímã" },
    { questao: 35, cor: "Vermelho", resposta: "tomada" },
    { questao: 36, cor: "Verde", resposta: "chama" },
    { questao: 37, cor: "Amarelo", resposta: "giz" },
    { questao: 38, cor: "Verde", resposta: "tubo de ensaio" },
    { questao: 39, cor: "Azul", resposta: "ímã" },
    { questao: 40, cor: "Amarelo", resposta: "metal" },
    { questao: 41, cor: "Azul", resposta: "metal" },
    { questao: 42, cor: "Azul", resposta: "pólos" },
    { questao: 43, cor: "Amarelo", resposta: "bússola" },
    { questao: 44, cor: "Verde", resposta: "orientar" },
    { questao: 45, cor: "Verde", resposta: "D (Ótica)" },
    { questao: 46, cor: "Amarelo", resposta: "F (Magnetismo)" },
    { questao: 47, cor: "Vermelho", resposta: "E (Eletricidade)" },
    { questao: 48, cor: "Azul", resposta: "A (Acústica)" },
    { questao: 49, cor: "Amarelo", resposta: "B (Mecânica)" },
    { questao: 50, cor: "Verde", resposta: "C (Termodinâmica)" },
    { questao: 51, cor: "Verde", resposta: "ESMERALDA" },
    { questao: 52, cor: "Amarelo", resposta: "TOPÁZIO" },
    { questao: 53, cor: "Vermelho", resposta: "RUBI" },
    { questao: 54, cor: "Azul", resposta: "TURQUESA" },
    { questao: 55, cor: "Azul", resposta: "AMETISTA" },
    { questao: 56, cor: "Verde", resposta: "DIAMANTE" },
    { questao: 57, cor: "Amarelo", resposta: "TOPÁZIO" },
    { questao: 58, cor: "Azul", resposta: "ÁGUA MARINHA" },
    { questao: 59, cor: "Vermelho", resposta: "RUBI" },
    { questao: 60, cor: "Azul", resposta: "cinza" },
  ],
  programa_3: [
    { questao: 61, cor: "Amarelo", resposta: "pássaro" },
    { questao: 62, cor: "Vermelho", resposta: "despertador" },
    { questao: 63, cor: "Azul", resposta: "trompete" },
    { questao: 64, cor: "Vermelho", resposta: "som forte" },
    { questao: 65, cor: "Amarelo", resposta: "som forte" },
    { questao: 66, cor: "Verde", resposta: "som forte" },
    { questao: 67, cor: "Verde", resposta: "quentes" },
    { questao: 68, cor: "Verde", resposta: "calor" },
    { questao: 69, cor: "Azul", resposta: "esquentar" },
    { questao: 70, cor: "Amarelo", resposta: "bom" },
    { questao: 71, cor: "Verde", resposta: "derreter" },
    { questao: 72, cor: "Verde", resposta: "madeira" },
    { questao: 73, cor: "Vermelho", resposta: "mau" },
    { questao: 74, cor: "Azul", resposta: "Sonic" },
    { questao: 75, cor: "Vermelho", resposta: "caracol" },
    { questao: 76, cor: "Amarelo", resposta: "foguete" },
    { questao: 77, cor: "Vermelho", resposta: "pena" },
    { questao: 78, cor: "Verde", resposta: "elefante" },
    { questao: 79, cor: "Amarelo", resposta: "Sol" },
    { questao: 80, cor: "Vermelho", resposta: "gelo" },
    { questao: 81, cor: "Azul", resposta: "chocolate" },
    { questao: 82, cor: "Vermelho", resposta: "fornecem" },
    { questao: 83, cor: "Verde", resposta: "Sonic" },
    { questao: 84, cor: "Verde", resposta: "hot dog" },
    { questao: 85, cor: "Amarelo", resposta: "doces" },
    { questao: 86, cor: "Azul", resposta: "fritas" },
    { questao: 87, cor: "Azul", resposta: "C" },
    { questao: 88, cor: "Vermelho", resposta: "A" },
    { questao: 89, cor: "Verde", resposta: "D" },
    { questao: 90, cor: "Amarelo", resposta: "B" },
  ],
  programa_4: [
    { questao: 91, cor: "Amarelo", resposta: "olhos" },
    { questao: 92, cor: "Vermelho", resposta: "mão" },
    { questao: 93, cor: "Verde", resposta: "cheiro" },
    { questao: 94, cor: "Azul", resposta: "nariz" },
    { questao: 95, cor: "Amarelo", resposta: "língua" },
    { questao: 96, cor: "Azul", resposta: "ouvidos" },
    { questao: 97, cor: "Verde", resposta: "pele" },
    { questao: 98, cor: "Amarelo", resposta: "B" },
    { questao: 99, cor: "Azul", resposta: "C" },
    { questao: 100, cor: "Vermelho", resposta: "A" },
    { questao: 101, cor: "Verde", resposta: "F" },
    { questao: 102, cor: "Vermelho", resposta: "E" },
    { questao: 103, cor: "Azul", resposta: "D" },
    { questao: 104, cor: "Vermelho", resposta: "esquenta" },
    { questao: 105, cor: "Verde", resposta: "ferve" },
    { questao: 106, cor: "Azul", resposta: "vapor" },
    { questao: 107, cor: "Amarelo", resposta: "congela" },
    { questao: 108, cor: "Vermelho", resposta: "gelo" },
    { questao: 109, cor: "Amarelo", resposta: "derrete" },
    { questao: 110, cor: "Azul", resposta: "água" },
    { questao: 111, cor: "Amarelo", resposta: "emagreceu" },
    { questao: 112, cor: "Azul", resposta: "esvaziou" },
    { questao: 113, cor: "Azul", resposta: "magro" },
    { questao: 114, cor: "Amarelo", resposta: "parar" },
    { questao: 115, cor: "Vermelho", resposta: "pouco" },
    { questao: 116, cor: "Azul", resposta: "descer" },
    { questao: 117, cor: "Azul", resposta: "planetas" },
    { questao: 118, cor: "Verde", resposta: "Terra" },
    { questao: 119, cor: "Vermelho", resposta: "Lua" },
    { questao: 120, cor: "Verde", resposta: "Saturno" },
  ],
  programa_5: [
    { questao: 121, cor: "Azul", resposta: "Sol" },
    { questao: 122, cor: "Azul", resposta: "Gelo" },
    { questao: 123, cor: "Amarelo", resposta: "Pinguim" },
    { questao: 124, cor: "Verde", resposta: "Abacaxi" },
    { questao: 125, cor: "Vermelho", resposta: "Papagaio" },
    { questao: 126, cor: "Vermelho", resposta: "Alho" },
    { questao: 127, cor: "Azul", resposta: "Banana (Buzz Bomber)" },
    { questao: 128, cor: "Verde", resposta: "Jacaré (Jaws)" },
    { questao: 129, cor: "Amarelo", resposta: "Minhoca (Moto Bug)" },
    { questao: 130, cor: "Amarelo", resposta: "Cavalo (Caterkiller)" },
    { questao: 131, cor: "Verde", resposta: "Régua (Roller)" },
    { questao: 132, cor: "Verde", resposta: "Sapato (Spikes)" },
    { questao: 133, cor: "Amarelo", resposta: "Nuvem (Newtron)" },
    { questao: 134, cor: "Vermelho", resposta: "Máquina" },
    { questao: 135, cor: "Amarelo", resposta: "Máquina" },
    { questao: 136, cor: "Azul", resposta: "Máquina" },
    { questao: 137, cor: "Verde", resposta: "Máquina" },
    { questao: 138, cor: "Vermelho", resposta: "Máquina" },
    { questao: 139, cor: "Azul", resposta: "Máquina" },
    { questao: 140, cor: "Verde", resposta: "Máquina" },
    { questao: 141, cor: "Verde", resposta: "D" },
    { questao: 142, cor: "Amarelo", resposta: "E" },
    { questao: 143, cor: "Vermelho", resposta: "A" },
    { questao: 144, cor: "Azul", resposta: "F" },
    { questao: 145, cor: "Amarelo", resposta: "B" },
    { questao: 146, cor: "Verde", resposta: "C" },
    { questao: 147, cor: "Vermelho", resposta: "1, 6, 10, 14 (Sally)" },
    { questao: 148, cor: "Amarelo", resposta: "5, 4, 9, 16 (Chirps)" },
    { questao: 149, cor: "Vermelho", resposta: "9, 2, 5, 16 (Tux)" },
    { questao: 150, cor: "Amarelo", resposta: "13, 2, 7, 12 (Joe Sushi)" },
  ],
};
