export type GabaritoCor = "Vermelho" | "Amarelo" | "Azul" | "Verde";

export type GabaritoItem = {
  questao: number;
  cor: GabaritoCor;
  resposta: string;
};

export type GabaritoPenseBem = {
  programa_1: GabaritoItem[];
  programa_2: GabaritoItem[];
  programa_3: GabaritoItem[];
  programa_4: GabaritoItem[];
  programa_5: GabaritoItem[];
};

export const GABARITO_PENSE_BEM: GabaritoPenseBem = {
  programa_1: [
    { questao: 1, cor: "Verde", resposta: "équidna" },
    { questao: 2, cor: "Vermelho", resposta: "espinhos" },
    { questao: 3, cor: "Vermelho", resposta: "comprida e fina" },
    { questao: 4, cor: "Verde", resposta: "unhas" },
    { questao: 5, cor: "Verde", resposta: "escavar buracos na terra" },
    { questao: 6, cor: "Amarelo", resposta: "4 patas" },
    { questao: 7, cor: "Amarelo", resposta: "2 minutos" },
    { questao: 8, cor: "Azul", resposta: "baleia azul" },
    { questao: 9, cor: "Vermelho", resposta: "peixe-boi" },
    { questao: 10, cor: "Verde", resposta: "guepardo" },
    { questao: 11, cor: "Amarelo", resposta: "preguiça-de-três-dedos" },
    { questao: 12, cor: "Vermelho", resposta: "60 km/h" },
    { questao: 13, cor: "Vermelho", resposta: "54 metros por hora" },
    { questao: 14, cor: "Verde", resposta: "710" },
    { questao: 15, cor: "Azul", resposta: "250 milhões" },
    { questao: 16, cor: "Amarelo", resposta: "gorila" },
    { questao: 17, cor: "Vermelho", resposta: "urso de Kodiak" },
    { questao: 18, cor: "Amarelo", resposta: "morcego" },
    { questao: 19, cor: "Verde", resposta: "capivara" },
    { questao: 20, cor: "Vermelho", resposta: "cão fila" },
    { questao: 21, cor: "Azul", resposta: "tiranossauro Rex" },
    { questao: 22, cor: "Vermelho", resposta: "75 milhões de anos" },
    { questao: 23, cor: "Azul", resposta: "100 toneladas" },
    { questao: 24, cor: "Azul", resposta: "1,36 m x 81 cm" },
    { questao: 25, cor: "Amarelo", resposta: "70 gramas" },
    { questao: 26, cor: "Verde", resposta: "régua" },
    { questao: 27, cor: "Vermelho", resposta: "pterossauro" },
    { questao: 28, cor: "Amarelo", resposta: "12 metros" },
    { questao: 29, cor: "Vermelho", resposta: "répteis" },
    { questao: 30, cor: "Amarelo", resposta: "lagarto" },
  ],
  programa_2: [
    { questao: 31, cor: "Verde", resposta: "Groenlândia" },
    { questao: 32, cor: "Vermelho", resposta: "Bananal" },
    { questao: 33, cor: "Azul", resposta: "Fernando de Noronha" },
    { questao: 34, cor: "Vermelho", resposta: "um conjunto de ilhas" },
    { questao: 35, cor: "Azul", resposta: "acidentes geográficos" },
    { questao: 36, cor: "Azul", resposta: "que bóia" },
    { questao: 37, cor: "Amarelo", resposta: "minerais" },
    { questao: 38, cor: "Verde", resposta: "Brasil" },
    { questao: 39, cor: "Verde", resposta: "diamante" },
    { questao: 40, cor: "Verde", resposta: "gema" },
    { questao: 41, cor: "Amarelo", resposta: "dura" },
    { questao: 42, cor: "Verde", resposta: "vidro" },
    { questao: 43, cor: "Vermelho", resposta: "Via Láctea" },
    { questao: 44, cor: "Azul", resposta: "Júpiter" },
    { questao: 45, cor: "Vermelho", resposta: "Sirius" },
    { questao: 46, cor: "Verde", resposta: "Sol" },
    { questao: 47, cor: "Vermelho", resposta: "Plutão" },
    { questao: 48, cor: "Verde", resposta: "Vênus" },
    { questao: 49, cor: "Amarelo", resposta: "Saturno" },
    { questao: 50, cor: "Azul", resposta: "Saturno" },
    { questao: 51, cor: "Amarelo", resposta: "Equador" },
    { questao: 52, cor: "Azul", resposta: "Amazonas" },
    { questao: 53, cor: "Vermelho", resposta: "Saara" },
    { questao: 54, cor: "Vermelho", resposta: "México" },
    { questao: 55, cor: "Amarelo", resposta: "Pacífico" },
    { questao: 56, cor: "Vermelho", resposta: "Everest" },
    { questao: 57, cor: "Amarelo", resposta: "TITÃS" },
    { questao: 58, cor: "Amarelo", resposta: "DAVI" },
    { questao: 59, cor: "Amarelo", resposta: "SEQUÓIAS" },
    { questao: 60, cor: "Amarelo", resposta: "2,31 m" },
  ],
  programa_3: [
    { questao: 61, cor: "Azul", resposta: "morangos" },
    { questao: 62, cor: "Verde", resposta: "Austrália" },
    { questao: 63, cor: "Azul", resposta: "Wisconsin" },
    { questao: 64, cor: "Verde", resposta: "ovos" },
    { questao: 65, cor: "Verde", resposta: "1988" },
    { questao: 66, cor: "Verde", resposta: "1.000" },
    { questao: 67, cor: "Vermelho", resposta: "quarto" },
    { questao: 68, cor: "Azul", resposta: "52" },
    { questao: 69, cor: "Vermelho", resposta: "Romário" },
    { questao: 70, cor: "Vermelho", resposta: "94" },
    { questao: 71, cor: "Amarelo", resposta: "Brasil" },
    { questao: 72, cor: "Azul", resposta: "162" },
    { questao: 73, cor: "Vermelho", resposta: "C (2,45m)" },
    { questao: 74, cor: "Vermelho", resposta: "A (23,12m)" },
    { questao: 75, cor: "Amarelo", resposta: "E (8,95m)" },
    { questao: 76, cor: "Amarelo", resposta: "F (95,66m)" },
    { questao: 77, cor: "Amarelo", resposta: "D (6,14m)" },
    { questao: 78, cor: "Verde", resposta: "H (74,08m)" },
    { questao: 79, cor: "Verde", resposta: "B (86,74m)" },
    { questao: 80, cor: "Azul", resposta: "G (17,97m)" },
    { questao: 81, cor: "Azul", resposta: "chuchu" },
    { questao: 82, cor: "Amarelo", resposta: "concerto" },
    { questao: 83, cor: "Vermelho", resposta: "assinar" },
    { questao: 84, cor: "Verde", resposta: "exceção" },
    { questao: 85, cor: "Amarelo", resposta: "açúcar" },
    { questao: 86, cor: "Vermelho", resposta: "xícara" },
    { questao: 87, cor: "Verde", resposta: "BANDO" },
    { questao: 88, cor: "Amarelo", resposta: "CARDUME" },
    { questao: 89, cor: "Amarelo", resposta: "CONSTELAÇÃO" },
    { questao: 90, cor: "Verde", resposta: "ALCATÉIA" },
  ],
  programa_4: [
    { questao: 91, cor: "Amarelo", resposta: "recente" },
    { questao: 92, cor: "Verde", resposta: "dons" },
    { questao: 93, cor: "Azul", resposta: "origem" },
    { questao: 94, cor: "Amarelo", resposta: "aniquilado" },
    { questao: 95, cor: "Vermelho", resposta: "demente" },
    { questao: 96, cor: "Verde", resposta: "boiar" },
    { questao: 97, cor: "Amarelo", resposta: "NEVE" },
    { questao: 98, cor: "Vermelho", resposta: "FERVENTE" },
    { questao: 99, cor: "Verde", resposta: "ZELÂNDIA" },
    { questao: 100, cor: "Amarelo", resposta: "RICHTER" },
    { questao: 101, cor: "Amarelo", resposta: "MAUNA LOA" },
    { questao: 102, cor: "Verde", resposta: "LAVA" },
    { questao: 103, cor: "Azul", resposta: "FOGO" },
    { questao: 104, cor: "Vermelho", resposta: "C (China)" },
    { questao: 105, cor: "Vermelho", resposta: "D (São Paulo)" },
    { questao: 106, cor: "Vermelho", resposta: "G (Estados Unidos)" },
    { questao: 107, cor: "Azul", resposta: "B (Rio de Janeiro)" },
    { questao: 108, cor: "Verde", resposta: "F (Orlando)" },
    { questao: 109, cor: "Vermelho", resposta: "A (Egito)" },
    { questao: 110, cor: "Azul", resposta: "E (Japão)" },
    { questao: 111, cor: "Azul", resposta: "Neil Armstrong" },
    { questao: 112, cor: "Azul", resposta: "Amir Klink" },
    { questao: 113, cor: "Verde", resposta: "Alemanha" },
    { questao: 114, cor: "Verde", resposta: "515,3" },
    { questao: 115, cor: "Azul", resposta: "Moscou" },
    { questao: 116, cor: "Azul", resposta: "ultrapassam" },
    { questao: 117, cor: "Vermelho", resposta: "B (Esmeralda)" },
    { questao: 118, cor: "Azul", resposta: "D (Nave)" },
    { questao: 119, cor: "Vermelho", resposta: "C (Uvas)" },
    { questao: 120, cor: "Azul", resposta: "A (Helicóptero)" },
  ],
  programa_5: [
    { questao: 121, cor: "Verde", resposta: "O Parque dos Dinossauros" },
    { questao: 122, cor: "Verde", resposta: "Batman" },
    { questao: 123, cor: "Amarelo", resposta: "Esqueceram de Mim" },
    { questao: 124, cor: "Azul", resposta: "Conde Drácula" },
    { questao: 125, cor: "Verde", resposta: "Universal City" },
    { questao: 126, cor: "Azul", resposta: "1975" },
    { questao: 127, cor: "Amarelo", resposta: "C (Hidrogênio)" },
    { questao: 128, cor: "Amarelo", resposta: "D (Ferro)" },
    { questao: 129, cor: "Verde", resposta: "F (Itaipu)" },
    { questao: 130, cor: "Vermelho", resposta: "B (Fukushima)" },
    { questao: 131, cor: "Azul", resposta: "A (IBM)" },
    { questao: 132, cor: "Amarelo", resposta: "G (Harper Lake Site)" },
    { questao: 133, cor: "Vermelho", resposta: "E (Radônio)" },
    { questao: 134, cor: "Amarelo", resposta: "Atlântida" },
    { questao: 135, cor: "Azul", resposta: "Eufrates" },
    { questao: 136, cor: "Vermelho", resposta: "Creta" },
    { questao: 137, cor: "Amarelo", resposta: "navegadores" },
    { questao: 138, cor: "Verde", resposta: "México" },
    { questao: 139, cor: "Verde", resposta: "Macedônia" },
    { questao: 140, cor: "Verde", resposta: "Jerusalém" },
    { questao: 141, cor: "Verde", resposta: "D (Entrada da Caverna)" },
    { questao: 142, cor: "Vermelho", resposta: "E (Pé de trás)" },
    { questao: 143, cor: "Amarelo", resposta: "B (Topo do Vulcão)" },
    { questao: 144, cor: "Vermelho", resposta: "F (Pé da frente)" },
    { questao: 145, cor: "Vermelho", resposta: "A (Céu e Montanha)" },
    { questao: 146, cor: "Vermelho", resposta: "C (Braço e Cabelo)" },
    { questao: 147, cor: "Vermelho", resposta: "1, 6, 11, 16" },
    { questao: 148, cor: "Azul", resposta: "5, 14, 15, 12" },
    { questao: 149, cor: "Azul", resposta: "9, 10, 7, 8" },
    { questao: 150, cor: "Amarelo", resposta: "13, 2, 3, 4" },
  ],
};
