import type { GabaritoPenseBem } from "./081";

export const GABARITO_PENSE_BEM: GabaritoPenseBem = {
  programa_1: [
    { questao: 1, cor: "Amarelo", resposta: "porco-espinho" },
    { questao: 2, cor: "Vermelho", resposta: "Ataque Giratório Supersônico" },
    { questao: 3, cor: "Azul", resposta: "azuis" },
    { questao: 4, cor: "Verde", resposta: "vermelhas" },
    { questao: 5, cor: "Verde", resposta: "cientista / laboratório" },
    { questao: 6, cor: "Amarelo", resposta: "Dr. Ivo Robotnik" },
    { questao: 7, cor: "Vermelho", resposta: "rabos" },
    { questao: 8, cor: "Azul", resposta: "helicóptero" },
    { questao: 9, cor: "Amarelo", resposta: "balão" },
    { questao: 10, cor: "Verde", resposta: "mais" },
    { questao: 11, cor: "Amarelo", resposta: "foguete" },
    { questao: 12, cor: "Verde", resposta: "leves" },
    { questao: 13, cor: "Vermelho", resposta: "trem-bala" },
    { questao: 14, cor: "Vermelho", resposta: "guepardo" },
    { questao: 15, cor: "Azul", resposta: "peixe-voador" },
    { questao: 16, cor: "Azul", resposta: "águia" },
    { questao: 17, cor: "Vermelho", resposta: "ultrapassam" },
    { questao: 18, cor: "Azul", resposta: "mais" },
    { questao: 19, cor: "Azul", resposta: "velocidade" },
    { questao: 20, cor: "Amarelo", resposta: "rápido" },
    { questao: 21, cor: "Vermelho", resposta: "invisíveis" },
    { questao: 22, cor: "Vermelho", resposta: "devagar" },
    { questao: 23, cor: "Amarelo", resposta: "peludos" },
    { questao: 24, cor: "Vermelho", resposta: "depressa" },
    { questao: 25, cor: "Amarelo", resposta: "helicóptero" },
    { questao: 26, cor: "Verde", resposta: "liquidificador" },
    { questao: 27, cor: "Vermelho", resposta: "ventilador" },
    { questao: 28, cor: "Azul", resposta: "hélice" },
    { questao: 29, cor: "Vermelho", resposta: "cata-vento" },
    { questao: 30, cor: "Azul", resposta: "moinho" },
  ],
  programa_2: [
    { questao: 31, cor: "Azul", resposta: "1,2,6,8,9,13,14" },
    { questao: 32, cor: "Amarelo", resposta: "1,2,3,7,12,16" },
    { questao: 33, cor: "Vermelho", resposta: "Sonic está correndo com Tails" },
    { questao: 34, cor: "Verde", resposta: "5,9,13,11,14,7" },
    { questao: 35, cor: "Azul", resposta: "4,15,1,10,2,9" },
    { questao: 36, cor: "Vermelho", resposta: "1,16,11,5,3" },
    { questao: 37, cor: "Verde", resposta: "mais" },
    { questao: 38, cor: "Vermelho", resposta: "descansar" },
    { questao: 39, cor: "Amarelo", resposta: "tartaruga" },
    { questao: 40, cor: "Vermelho", resposta: "lento" },
    { questao: 41, cor: "Azul", resposta: "longe" },
    { questao: 42, cor: "Verde", resposta: "desistiu" },
    { questao: 43, cor: "Vermelho", resposta: "competir" },
    { questao: 44, cor: "Azul", resposta: "vencer" },
    { questao: 45, cor: "Verde", resposta: "F" },
    { questao: 46, cor: "Vermelho", resposta: "A" },
    { questao: 47, cor: "Amarelo", resposta: "B" },
    { questao: 48, cor: "Azul", resposta: "D" },
    { questao: 49, cor: "Verde", resposta: "C" },
    { questao: 50, cor: "Vermelho", resposta: "E" },
    { questao: 51, cor: "Vermelho", resposta: "B" },
    { questao: 52, cor: "Azul", resposta: "E" },
    { questao: 53, cor: "Vermelho", resposta: "A" },
    { questao: 54, cor: "Verde", resposta: "D" },
    { questao: 55, cor: "Azul", resposta: "C" },
    { questao: 56, cor: "Amarelo", resposta: "F" },
    { questao: 57, cor: "Verde", resposta: "SONIC" },
    { questao: 58, cor: "Azul", resposta: "GOSTA" },
    { questao: 59, cor: "Verde", resposta: "DE" },
    { questao: 60, cor: "Verde", resposta: "CORRER" },
  ],
  programa_3: [
    { questao: 61, cor: "Verde", resposta: "foguete" },
    { questao: 62, cor: "Vermelho", resposta: "carro F1" },
    { questao: 63, cor: "Azul", resposta: "guepardo" },
    { questao: 64, cor: "Vermelho", resposta: "tubarão" },
    { questao: 65, cor: "Vermelho", resposta: "trem-bala" },
    { questao: 66, cor: "Amarelo", resposta: "águia" },
    { questao: 67, cor: "Azul", resposta: "Os pés de Sonic giram como rodas." },
    {
      questao: 68,
      cor: "Vermelho",
      resposta: "Ele escavou um túnel na montanha.",
    },
    { questao: 69, cor: "Verde", resposta: "Sonic usa luvas brancas." },
    {
      questao: 70,
      cor: "Vermelho",
      resposta: "Nosso amigo corre em alta velocidade.",
    },
    { questao: 71, cor: "Amarelo", resposta: "Fogo e lava são muito quentes." },
    {
      questao: 72,
      cor: "Vermelho",
      resposta: "Pedras vulcânicas voam para o alto.",
    },
    { questao: 73, cor: "Amarelo", resposta: "gasolina" },
    { questao: 74, cor: "Amarelo", resposta: "pés" },
    { questao: 75, cor: "Amarelo", resposta: "eletricidade" },
    { questao: 76, cor: "Azul", resposta: "vento" },
    { questao: 77, cor: "Amarelo", resposta: "carvão" },
    { questao: 78, cor: "Vermelho", resposta: "bateria" },
    { questao: 79, cor: "Verde", resposta: "ar" },
    { questao: 80, cor: "Amarelo", resposta: "pilha" },
    { questao: 81, cor: "Amarelo", resposta: "Balão" },
    { questao: 82, cor: "Amarelo", resposta: "Planador" },
    { questao: 83, cor: "Amarelo", resposta: "14-Bis" },
    { questao: 84, cor: "Vermelho", resposta: "Biplano" },
    { questao: 85, cor: "Azul", resposta: "Caça" },
    { questao: 86, cor: "Amarelo", resposta: "Ônibus espacial" },
    { questao: 87, cor: "Verde", resposta: "derreteu" },
    { questao: 88, cor: "Azul", resposta: "mar" },
    { questao: 89, cor: "Amarelo", resposta: "Santos Dumont" },
    { questao: 90, cor: "Vermelho", resposta: "asa-delta" },
  ],
  programa_4: [
    { questao: 91, cor: "Verde", resposta: "ar" },
    { questao: 92, cor: "Azul", resposta: "em volta" },
    { questao: 93, cor: "Vermelho", resposta: "esquentam" },
    { questao: 94, cor: "Verde", resposta: "leve" },
    { questao: 95, cor: "Amarelo", resposta: "sobe" },
    { questao: 96, cor: "Amarelo", resposta: "desce" },
    { questao: 97, cor: "Verde", resposta: "ventos" },
    { questao: 98, cor: "Azul", resposta: "brisa" },
    { questao: 99, cor: "Vermelho", resposta: "ventania" },
    { questao: 100, cor: "Vermelho", resposta: "furacão" },
    { questao: 101, cor: "Verde", resposta: "ciclone" },
    { questao: 102, cor: "Vermelho", resposta: "Equador" },
    { questao: 103, cor: "Verde", resposta: "som" },
    { questao: 104, cor: "Azul", resposta: "antes" },
    { questao: 105, cor: "Amarelo", resposta: "mais" },
    { questao: 106, cor: "Azul", resposta: "supersônico" },
    { questao: 107, cor: "Azul", resposta: "não" },
    { questao: 108, cor: "Verde", resposta: "luz" },
    { questao: 109, cor: "Verde", resposta: "Sol" },
    { questao: 110, cor: "Azul", resposta: "365" },
    { questao: 111, cor: "Azul", resposta: "clarão" },
    { questao: 112, cor: "Azul", resposta: "barulho" },
    { questao: 113, cor: "Verde", resposta: "elétrica" },
    { questao: 114, cor: "Vermelho", resposta: "relâmpago" },
    { questao: 115, cor: "Vermelho", resposta: "trovão" },
    { questao: 116, cor: "Azul", resposta: "altos" },
    { questao: 117, cor: "Amarelo", resposta: "A" },
    { questao: 118, cor: "Verde", resposta: "B" },
    { questao: 119, cor: "Azul", resposta: "C" },
    { questao: 120, cor: "Vermelho", resposta: "D" },
  ],
  programa_5: [
    { questao: 121, cor: "Verde", resposta: "correr" },
    { questao: 122, cor: "Amarelo", resposta: "nadar" },
    { questao: 123, cor: "Amarelo", resposta: "águia" },
    { questao: 124, cor: "Verde", resposta: "sapo" },
    { questao: 125, cor: "Vermelho", resposta: "lambaris" },
    { questao: 126, cor: "Amarelo", resposta: "mais" },
    { questao: 127, cor: "Azul", resposta: "D" },
    { questao: 128, cor: "Vermelho", resposta: "E" },
    { questao: 129, cor: "Verde", resposta: "C" },
    { questao: 130, cor: "Vermelho", resposta: "A" },
    { questao: 131, cor: "Azul", resposta: "B" },
    { questao: 132, cor: "Vermelho", resposta: "F" },
    { questao: 133, cor: "Amarelo", resposta: "GIRA" },
    { questao: 134, cor: "Azul", resposta: "MERGULHA" },
    { questao: 135, cor: "Azul", resposta: "SALTAR" },
    { questao: 136, cor: "Azul", resposta: "CORRER" },
    { questao: 137, cor: "Verde", resposta: "ATACAR" },
    { questao: 138, cor: "Azul", resposta: "VOAR" },
    { questao: 139, cor: "Vermelho", resposta: "A" },
    { questao: 140, cor: "Amarelo", resposta: "B" },
    { questao: 141, cor: "Azul", resposta: "C" },
    { questao: 142, cor: "Verde", resposta: "D" },
    { questao: 143, cor: "Vermelho", resposta: "E" },
    { questao: 144, cor: "Amarelo", resposta: "F" },
    { questao: 145, cor: "Azul", resposta: "G" },
    { questao: 146, cor: "Verde", resposta: "H" },
    { questao: 147, cor: "Verde", resposta: "esquiando" },
    { questao: 148, cor: "Azul", resposta: "mergulhando" },
    { questao: 149, cor: "Vermelho", resposta: "gelo" },
    { questao: 150, cor: "Amarelo", resposta: "montanha" },
  ],
};
